# Generated by Django 3.2.16 on 2023-01-27 15:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='map_coordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=2),
        ),
    ]
