# Generated by Django 3.2.16 on 2023-02-27 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0002_remove_intervention_zone'),
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='intervention',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interventions.intervention'),
        ),
        migrations.AlterField(
            model_name='pipeacces',
            name='pipe_access_type',
            field=models.CharField(choices=[('HouseValve', 'House Valve'), ('FirePole', 'Fire Pole'), ('FireHydrantValve', 'Fire Hydrant Valve'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
