# Generated by Django 3.2.16 on 2023-02-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='zone_area',
            field=models.FloatField(default=0),
        ),
    ]
