# Generated by Django 3.2.16 on 2023-01-28 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipe',
            old_name='zone_coordinates',
            new_name='pipe_coordinates',
        ),
    ]
