# Generated by Django 3.2.16 on 2023-02-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_zone_zone_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='zone_color',
            field=models.CharField(choices=[('green', 'Green'), ('orange', 'Orange'), ('red', 'Red')], default='Orange', max_length=20),
        ),
    ]
