# Generated by Django 3.2.16 on 2023-01-27 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_alter_map_map_coordinates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='map_coordinates',
            new_name='map_coordinate',
        ),
    ]
