# Generated by Django 3.2.16 on 2023-03-01 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0002_remove_intervention_zone'),
        ('maps', '0003_alter_zone_intervention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='intervention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interventions.intervention'),
        ),
    ]
