# Generated by Django 3.2.16 on 2023-01-20 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_alter_zone_zone_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='map_photo',
        ),
    ]
