# Generated by Django 3.2.16 on 2023-01-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_remove_map_map_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leakervehicle',
            name='map',
        ),
        migrations.RemoveField(
            model_name='map',
            name='leakervehicle_number',
        ),
        migrations.RemoveField(
            model_name='map',
            name='pipe_number',
        ),
        migrations.RemoveField(
            model_name='map',
            name='sensor_number',
        ),
        migrations.RemoveField(
            model_name='map',
            name='zone_number',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='map',
        ),
        migrations.RemoveField(
            model_name='pipe',
            name='map',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='map',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='map',
        ),
        migrations.AddField(
            model_name='map',
            name='leaker_vehicles',
            field=models.ManyToManyField(to='maps.LeakerVehicle'),
        ),
        migrations.AddField(
            model_name='map',
            name='pipes',
            field=models.ManyToManyField(to='maps.Pipe'),
        ),
        migrations.AddField(
            model_name='map',
            name='sensors',
            field=models.ManyToManyField(to='maps.Sensor'),
        ),
        migrations.AddField(
            model_name='map',
            name='zones',
            field=models.ManyToManyField(to='maps.Zone'),
        ),
    ]
