# Generated by Django 3.2.16 on 2023-02-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_alter_zone_zone_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='zone_color',
            field=models.CharField(choices=[('#97c900', 'Green'), ('#fc8d49', 'Orange'), ('#ff1919', 'Red')], default='orange', max_length=20),
        ),
    ]
