# Generated by Django 3.2.16 on 2023-01-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_auto_20230121_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leakervehicle',
            name='map',
        ),
        migrations.RemoveField(
            model_name='pipe',
            name='map',
        ),
        migrations.RemoveField(
            model_name='pipeacces',
            name='map',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='map',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='map',
        ),
        migrations.AddField(
            model_name='map',
            name='leaker_vehicles',
            field=models.ManyToManyField(blank=True, to='maps.LeakerVehicle'),
        ),
        migrations.AddField(
            model_name='map',
            name='pipes',
            field=models.ManyToManyField(blank=True, to='maps.Pipe'),
        ),
        migrations.AddField(
            model_name='map',
            name='sensors',
            field=models.ManyToManyField(blank=True, to='maps.Sensor'),
        ),
        migrations.AddField(
            model_name='map',
            name='zones',
            field=models.ManyToManyField(blank=True, to='maps.Zone'),
        ),
    ]
