# Generated by Django 3.2.16 on 2023-01-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_auto_20230121_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='leaker_vehicles',
            field=models.ManyToManyField(blank=True, related_name='maps', to='maps.LeakerVehicle'),
        ),
        migrations.AlterField(
            model_name='map',
            name='pipes',
            field=models.ManyToManyField(blank=True, related_name='maps', to='maps.Pipe'),
        ),
        migrations.AlterField(
            model_name='map',
            name='sensors',
            field=models.ManyToManyField(blank=True, related_name='maps', to='maps.Sensor'),
        ),
        migrations.AlterField(
            model_name='map',
            name='zones',
            field=models.ManyToManyField(blank=True, related_name='maps', to='maps.Zone'),
        ),
    ]
