# Generated by Django 3.2.16 on 2023-01-21 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_auto_20230121_0328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='leaker_vehicles',
        ),
        migrations.RemoveField(
            model_name='map',
            name='pipes',
        ),
        migrations.RemoveField(
            model_name='map',
            name='sensors',
        ),
        migrations.RemoveField(
            model_name='map',
            name='zones',
        ),
        migrations.AddField(
            model_name='map',
            name='leaker_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='maps.leakervehicle'),
        ),
        migrations.AddField(
            model_name='map',
            name='pipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='maps.pipe'),
        ),
        migrations.AddField(
            model_name='map',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='maps.sensor'),
        ),
        migrations.AddField(
            model_name='map',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='maps.zone'),
        ),
    ]
