# Generated by Django 3.2.16 on 2023-02-04 14:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_auto_20230201_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_frequency',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), blank=True, null=True, size=2),
        ),
    ]
