# Generated by Django 3.2.16 on 2023-01-21 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0011_auto_20230121_0340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='leakervehicle_number',
        ),
        migrations.RemoveField(
            model_name='map',
            name='pipe_number',
        ),
        migrations.RemoveField(
            model_name='map',
            name='sensor_number',
        ),
        migrations.RemoveField(
            model_name='map',
            name='zone_number',
        ),
        migrations.AlterField(
            model_name='map',
            name='leaker_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maps', to='maps.leakervehicle'),
        ),
        migrations.AlterField(
            model_name='map',
            name='pipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maps', to='maps.pipe'),
        ),
        migrations.AlterField(
            model_name='map',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maps', to='maps.sensor'),
        ),
        migrations.AlterField(
            model_name='map',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maps', to='maps.zone'),
        ),
    ]
