# Generated by Django 3.2.16 on 2023-02-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0011_alter_sensor_sensor_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='mark_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
