# Generated by Django 3.2.16 on 2023-01-21 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0012_auto_20230121_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='leaker_vehicle',
        ),
        migrations.RemoveField(
            model_name='map',
            name='pipe',
        ),
        migrations.RemoveField(
            model_name='map',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='map',
            name='zone',
        ),
        migrations.AddField(
            model_name='leakervehicle',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.map'),
        ),
        migrations.AddField(
            model_name='pipe',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.map'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.map'),
        ),
        migrations.AddField(
            model_name='zone',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maps', to='maps.map'),
        ),
    ]
