# Generated by Django 3.2.16 on 2023-01-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0013_auto_20230121_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='zone_num',
            field=models.IntegerField(default=0),
        ),
    ]
