# Generated by Django 3.2.16 on 2023-01-19 00:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('intervention_title', models.CharField(max_length=150)),
                ('intervention_description', models.TextField(blank=True)),
                ('intervention_type', models.CharField(choices=[('Hight', 'Hight'), ('Simple', 'Simple'), ('PipeSearch', 'Pipesearch')], default='Simple', max_length=50)),
                ('intervention_status', models.CharField(choices=[('NotStart', 'Notstart'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='NotStart', max_length=50)),
                ('intervention_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=15)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
