# Generated by Django 4.0.4 on 2023-01-10 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='client',
        ),
    ]
