# Generated by Django 3.2.16 on 2023-01-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='intervention_estimate_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='intervention',
            name='intervention_leak_tool',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
