# Generated by Django 3.2.16 on 2023-03-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0002_remove_intervention_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='address',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='zipcode',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
