# Generated by Django 3.2.16 on 2023-03-01 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0003_auto_20230301_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='intervention_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='intervention_estimate_time',
            field=models.DateField(blank=True),
        ),
    ]
