# Generated by Django 4.0.4 on 2023-01-10 00:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_title', models.CharField(max_length=150)),
                ('contract_description', models.TextField(blank=True)),
                ('contract_type', models.CharField(choices=[('Hight', 'Hight'), ('Simple', 'Simple'), ('PipeSearch', 'Pipesearch')], default='Simple', max_length=50)),
                ('contract_status', models.CharField(choices=[('NotStart', 'Notstart'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='NotStart', max_length=50)),
                ('contract_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=15)),
                ('is_published', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.client')),
            ],
        ),
    ]
