# Generated by Django 3.2.16 on 2023-02-27 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='zone',
        ),
    ]
