# Generated by Django 3.2.16 on 2023-01-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='is_published',
            field=models.BooleanField(),
        ),
    ]
