# Generated by Django 3.2.16 on 2023-03-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_remove_contract_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_estimate_end_date',
            field=models.DateField(blank=True),
        ),
    ]
