# Generated by Django 3.2.16 on 2023-03-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_contract_contract_estimate_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_work_type',
            field=models.CharField(blank=True, choices=[('Fire_Hydrant_Inspection', 'Fire Hydrant Inspection'), ('All_City_Inspections', 'All City Inspections'), ('Clarifying_the_location_of_the_leak', 'Clarify Leak Location'), ('Solve_high_consumption_problem_but_the_leak_is_not_identified', 'Solve High Consumption')], default='Fire_Hydrant_Inspection', max_length=200),
        ),
    ]
