# Generated by Django 3.2.16 on 2023-01-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_contract_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_work_type',
            field=models.CharField(choices=[('Fire Hydrant Inspection', 'Fire Hydrant Inspection'), ('All City Inspections', 'All City Inspections'), ('Clarifying the location of the leak', 'Clarify Leak Location'), ('Solve high consumption problem but the leak is not identified', 'Solve High Consumption')], default='Fire Hydrant Inspection', max_length=200),
        ),
    ]
