# Generated by Django 3.2.16 on 2023-01-25 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_contract_contract_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
