# Generated by Django 3.2.16 on 2023-01-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_auto_20230125_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='is_published',
            field=models.CharField(choices=[('is_published', 'Is Published'), ('iq_not_published', 'Is Not Published')], default='iq_not_published', max_length=50),
        ),
    ]
