# Generated by Django 3.2.16 on 2023-04-10 13:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=100)),
                ('user_role', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('add_sensor_coordinates', models.CharField(blank=True, max_length=100)),
                ('add_mark_coordinates', models.CharField(blank=True, max_length=100)),
                ('add_pipe_coordinates', models.CharField(blank=True, max_length=100)),
                ('add_pipe_access_coordinates', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='report_image')),
                ('report_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
