# Generated by Django 3.2.16 on 2023-03-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='add_mark_coordinates',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='add_pipe_access_coordinates',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='add_pipe_coordinates',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='add_sensor_coordinates',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
