# Generated by Django 3.2.16 on 2023-02-16 15:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='add_mark_coordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, size=2),
        ),
        migrations.AlterField(
            model_name='report',
            name='add_pipe_access_coordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, size=2),
        ),
        migrations.AlterField(
            model_name='report',
            name='add_pipe_coordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, size=2),
        ),
        migrations.AlterField(
            model_name='report',
            name='add_sensor_coordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, size=2),
        ),
    ]
