# Generated by Django 3.2.16 on 2023-02-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20230216_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='user_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='user_role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
