# Generated by Django 4.0.4 on 2023-01-10 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('clientNameContract', models.CharField(max_length=50)),
                ('contractData', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('interventionObject', models.CharField(max_length=50)),
                ('interventionType', models.CharField(max_length=50)),
                ('interventionDate', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='KpiTracking',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('LeakerKpi', models.CharField(max_length=50)),
                ('NumberOfLeak', models.IntegerField()),
                ('numWaterHyd', models.CharField(max_length=50)),
                ('distance', models.CharField(max_length=50)),
                ('leakerStartTime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50)),
                ('cityNumber', models.IntegerField()),
                ('stateNumber', models.IntegerField()),
                ('streets', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pipe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pipeNumber', models.IntegerField()),
                ('pipeStreet', models.CharField(max_length=50)),
                ('valves', models.CharField(max_length=50)),
                ('pipeType', models.CharField(max_length=50)),
                ('pipeColor', models.CharField(max_length=50)),
                ('pipeAcces', models.CharField(max_length=50)),
                ('map', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.map')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('reportObject', models.CharField(max_length=50)),
                ('senderName', models.CharField(max_length=50)),
                ('senderType', models.CharField(max_length=50)),
                ('reportDate', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('zoneCity', models.CharField(max_length=50)),
                ('zoneColor', models.CharField(max_length=50)),
                ('zoneCoordinates', models.IntegerField()),
                ('map', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.map')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sensorNumber', models.IntegerField()),
                ('sensorType', models.CharField(max_length=50)),
                ('sensorCoordinates', models.IntegerField()),
                ('sensorDetectionLength', models.IntegerField()),
                ('map', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.map')),
            ],
        ),
        migrations.CreateModel(
            name='Pipe_acces',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('streetValveCor', models.CharField(max_length=50)),
                ('houseValveCor', models.CharField(max_length=50)),
                ('fireValveCor', models.CharField(max_length=50)),
                ('pipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.pipe')),
            ],
        ),
    ]
