# Generated by Django 3.2.16 on 2023-02-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('is_admin', 'is_admin'), ('is_leaker', 'is_leaker'), ('is_client', 'is_client')], default='is_client', max_length=255),
        ),
    ]
